### ISSUE TITLE
希望可以缓冲几页

### ISSUE THREAD

**Issue by linrealp** [crowforkotlin/CopyMangaX#104]
目前好像是阅读到指定页面，才会开始加载图片，我是横屏滚动，跨页都会有转圈进度，希望可以提前加载几页。

**Comment by crowforkotlin** [comment]
此问题没法解决、目前看了下实现、几乎很难实现、但是在新版1.4.0中似乎进行了小优化、差不多就是在网络较好、滑动较慢的情况基本不会出现转圈进度和黑色未加载界面

**Comment by linrealp** [comment]
新版本已经看不到黑色加载界面了，问题已经解决，赞！
