### ISSUE TITLE
仅登录可见的漫画如相合之物，登录后也无法搜索得到，希望可以改进一下

### ISSUE THREAD

**Issue by yuduotianguang** [CrowForKotlin/CopyMangaX#21]

**Comment by CrowForKotlin** [comment]
这个只能尝试修复了  首先数据均是源自官网web 获取的。 经测试 官网web登陆后也无法搜索到《相合之物》目前只有官网app才可

**Comment by yuduotianguang** [comment]
> 这个只能尝试修复了  首先数据均是源自官网web 获取的。 经测试 官网web登陆后也无法搜索到《相合之物》目前只有官网app才可
> 

因为另一个fumiama做的是可以搜索得到的，感觉可以借鉴一下

**Comment by CrowForKotlin** [comment]
好的 谢谢 有空就去研究下

**Comment by CrowForKotlin** [comment]
> > 这个只能尝试修复了  首先数据均是源自官网web 获取的。 经测试 官网web登陆后也无法搜索到《相合之物》目前只有官网app才可
> 
> 因为另一个fumiama做的是可以搜索得到的，感觉可以借鉴一下

[已修复此问题](https://github.com/CrowForKotlin/CopyMangaX/commit/e799344329e4b54d53c9db770e5170eac0951787#diff-b9f592c9cae6fc92ea8788d855cf74cca3f2d3a048f7e371d54d6438e672c61f)
