### ISSUE TITLE
可以增加一个左右阅读方向功能吗

### ISSUE THREAD

**Issue by as996656503** [crowforkotlin/CopyMangaX#29]
如题 上下滑动有点不习惯

**Comment by CrowForKotlin** [comment]
好的👌 有空加看看加下这个新功能 之前已经在筹备了

**Comment by Sunosay** [comment]
+1 想问下 方便加个点击左右就直接翻页的功能吗

**Comment by CrowForKotlin** [comment]
> +1 想问下 方便加个点击左右就直接翻页的功能吗
没问题 我今晚就看看

**Comment by Sunosay** [comment]
> > +1 想问下 方便加个点击左右就直接翻页的功能吗
> > 没问题 我今晚就看看

非常感谢,大佬辛苦了_(:з)∠)_

**Comment by crowforkotlin** [comment]
#54

**Comment by lhjgege** [comment]
视屏播放全屏无返回按钮能否加一个
