### ISSUE TITLE
可以增加一个书架内漫画按更新时间排序的功能吗？

### ISSUE THREAD

**Issue by wxt12354** [CrowForKotlin/CopyMangaX#30]
目前书架上漫画按照收藏时间排序，不知道是我设置问题还是app本身排序问题。如果可以的话希望增加一个按照更新时间排序的功能。thx！

**Comment by yuduotianguang** [comment]
> 没问题 先等到后面做出阅读方式就开始这个

希望这个基础上增加一个更新前置，就是新更新的漫画移到最前

**Comment by CrowForKotlin** [comment]
> > 没问题 先等到后面做出阅读方式就开始这个
> 
> 希望这个基础上增加一个更新前置，就是新更新的漫画移到最前

这个是有的晚上我看下

**Comment by CrowForKotlin** [comment]
#[Dev 分支 efd284e 已完成](https://github.com/CrowForKotlin/CopyMangaX/commit/efd284e9fcb64b60101c5e0b4c84a43511d84c85)
