### ISSUE TITLE
希望增加评论区功能

### ISSUE THREAD

**Issue by GaoMengICT** [crowforkotlin/CopyMangaX#31]
拷贝漫画的官方APP有评论功能，网页端看不到，但是有插件可以参考[拷贝漫画PC显示评论](https://greasyfork.org/zh-CN/scripts/464656-%E6%8B%B7%E8%B4%9D%E6%BC%AB%E7%94%BBpc%E6%98%BE%E7%A4%BA%E8%AF%84%E8%AE%BA)，希望可以增加，谢谢！

**Comment by CrowForKotlin** [comment]
拷贝目前所有接口我都拿到了 评论功能只是没加
目前忙于工作  且该项目正在处理recyclerview的阅读方式，非常棘手

**Comment by crowforkotlin** [comment]
#54
