### ISSUE TITLE
移动网络用不了

### ISSUE THREAD

**Issue by 932749734** [CrowForKotlin/CopyMangaX#33]
不管是移动宽带还是移动流量，好像都什么都加载不出来。网页主站也是挂梯子才能上去

**Comment by CrowForKotlin** [comment]
这是正常的现象 我就是移动网络 没有任何问题（使用正常），问题可能有两个
第一个：这个就是你哪里dns被污染导致的 这个要解决只能尝试清理缓存或者换运营商和等一段时间，当然这只是一种可能性 
第二个：就是可以看下你在设置中是否设置了站点设置 为 站点①、代理是否是国内路线
第三个：拷贝本身站点就不稳定 可能和你所在区域有关系

**Comment by CrowForKotlin** [comment]
可以关闭该问题了吗

**Comment by CrowForKotlin** [comment]
我看下是否有新增的节点提供使用、有的话会更新

**Comment by CrowForKotlin** [comment]
可在 设置 - 站点设置 -  动态站点③ 这个已更新 无需Magic
