### ISSUE TITLE
如何解决，移动端请求章节图片api时，只发了5张图片的问题？

### ISSUE THREAD

**Issue by Minori-ty** [CrowForKotlin/CopyMangaX#34]
关于章节详情图片api，在电脑端请求会给完整的图片地址，而移动端请求时，只给了前5张图片的地址。修改了user-agent也不行，你是如何解决的？

**Comment by Minori-ty** [comment]
> 具体说下是什么接口

请求xx漫画的第x话的图片，https://api.mangacopy.com/api/v3/comic/nvyoudepengyou/chapter2/814c2e14-3a5c-11ee-be2e-d3d228a76de6?platform=1&_update=true

我用电脑网页端请求的时候，给出了完整的图片地址
但是改成用手机网页请求时，就只给了前五张图片

不过看了一下拷贝的手机网页端，好像也是只给了前五张，要求下载app才能看到完整的。
所以问一下你是怎么请求的？

**Comment by CrowForKotlin** [comment]
> > 具体说下是什么接口
> 
> 请求xx漫画的第x话的图片，https://api.mangacopy.com/api/v3/comic/nvyoudepengyou/chapter2/814c2e14-3a5c-11ee-be2e-d3d228a76de6?platform=1&_update=true
> 
> 我用电脑网页端请求的时候，给出了完整的图片地址 但是改成用手机网页请求时，就只给了前五张图片
> 
> 不过看了一下拷贝的手机网页端，好像也是只给了前五张，要求下载app才能看到完整的。 所以问一下你是怎么请求的？

请求头请设置 "Platform": "1"

**Comment by Minori-ty** [comment]
> 

设置了，还是不行
![image](https://github.com/CrowForKotlin/CopyMangaX/assets/79521943/862f9fbb-f4c5-4254-a749-fa9ba21b757f)
我把我的网站做成了在线，您有空的话可以看一下，https://comic-eight.vercel.app/#/home

电脑的话，在浏览器你可以切换成桌面端和移动端查看一下，桌面端时，则是完成显示；移动端时，则是只有前5张图片

**Comment by CrowForKotlin** [comment]
> > 
> 
> 设置了，还是不行 ![image](https://user-images.githubusercontent.com/79521943/261196264-862f9fbb-f4c5-4254-a749-fa9ba21b757f.png) 我把我的网站做成了在线，您有空的话可以看一下，https://comic-eight.vercel.app/#/home
> 
> 电脑的话，在浏览器你可以切换成桌面端和移动端查看一下，桌面端时，则是完成显示；移动端时，则是只有前5张图片

query params 的platform设置成3

**Comment by Minori-ty** [comment]
> > > 
> > 
> > 
> > 设置了，还是不行 ![image](https://user-images.githubusercontent.com/79521943/261196264-862f9fbb-f4c5-4254-a749-fa9ba21b757f.png) 我把我的网站做成了在线，您有空的话可以看一下，https://comic-eight.vercel.app/#/home
> > 电脑的话，在浏览器你可以切换成桌面端和移动端查看一下，桌面端时，则是完成显示；移动端时，则是只有前5张图片
> 
> query params 的platform设置成3

不行啊，改了之后还是没用
![image](https://github.com/CrowForKotlin/CopyMangaX/assets/79521943/46b67e77-93ac-4282-9c7f-387189c2c7dc)

**Comment by CrowForKotlin** [comment]
@Minori-ty QueryParams Platform = 3 Header Platform = 1 伪造User-Agent试试
![image](https://github.com/CrowForKotlin/CopyMangaX/assets/60876546/eb2e45a7-51e4-4015-b448-3f46af3679df)

**Comment by Minori-ty** [comment]
> User-Agent

我这边浏览器不允许伪造User-Agent，你是怎么请求的？

**Comment by CrowForKotlin** [comment]
![image](https://github.com/CrowForKotlin/CopyMangaX/assets/60876546/63f7661e-a52e-4f79-8020-2376265f2734)


> > User-Agent
> 
> 我这边浏览器不允许伪造User-Agent，你是怎么请求的？
