### ISSUE TITLE
關於收藏功能

### ISSUE THREAD

**Issue by david40322** [crowforkotlin/CopyMangaX#36]
"加入書櫃:收藏功能已失靈。 遇到喜歡的漫畫要收藏，會顯示unknown error。

 另外，"我的書櫃"可以調整成   最新更新的漫畫在最上面嗎?  亦即"更新日期從上到下"

**Comment by CrowForKotlin** [comment]
关于第一个问题 收藏功能失效 请提供更多的信息补充：Android版本、型号、“设置-动态站点选择的站点是什么” 、我这边正常测试可以添加没有任何问题

第二个需求后续更新会增加

**Comment by CrowForKotlin** [comment]
> 关于第一个问题 收藏功能失效 请提供更多的信息补充：Android版本、型号、“设置-动态站点选择的站点是什么” 、账号是否登陆？是否开启了代理？我这边正常测试可以添加没有任何问题
> 
> 第二个需求后续更新会增加

**Comment by david40322** [comment]
回報，看起來是一段時間後，就會要求重新登入。  重新登入後，就可以正常使用收藏功能了。

**Comment by CrowForKotlin** [comment]
> 回報，看起來是一段時間後，就會要求重新登入。 重新登入後，就可以正常使用收藏功能了。

其实 正常来说是不会这样的 发生这种情况的原因目前可能只有一个 就是你这个账号在其他的拷贝漫画应用登陆过 导致token失效需要重新登陆 出现unknow error可能是因为你这个登陆失效但是 token却仍然存在上一个导致的
