### ISSUE TITLE
作者的as编译工具使用的是预览版本吗？

### ISSUE THREAD

**Issue by lhjgege** [CrowForKotlin/CopyMangaX#41]
如题，在as最新的稳定版本都不能运行项目。尴尬中

**Comment by CrowForKotlin** [comment]
> 如题，在as最新的稳定版本都不能运行项目。尴尬中

很简单的问题 降低Gradle 版本 KT版本 COMPOSE 版本

我使用的AS 为 最新最不稳定的Canary版本

**Comment by CrowForKotlin** [comment]
> 如题，在as最新的稳定版本都不能运行项目。尴尬中

![image](https://github.com/CrowForKotlin/CopyMangaX/assets/60876546/d062d6f8-5b63-4c23-b01d-a892a0bde6a1)
