### ISSUE TITLE
bug report: 热度显示不正确

### ISSUE THREAD

**Issue by cyc4188** [crowforkotlin/CopyMangaX#42]
热度单位为w和k时显示不正确
官方app：
![Screenshot_2023-09-12-19-56-13-602_com.copymanga.app.jpg](https://github.com/CrowForKotlin/CopyMangaX/assets/40726077/efbb67f3-505e-4107-82b5-d8bdbe1357e8)

copyMangaX：
![Screenshot_2023-09-12-19-56-09-796_com.crow.copymanga.jpg](https://github.com/CrowForKotlin/CopyMangaX/assets/40726077/66113410-2aa0-4975-8b0f-e36d25d90b7d)

**Comment by CrowForKotlin** [comment]
这个显示是正常的 只是细化了具体内容  “，”逗号作为分隔符

**Comment by CrowForKotlin** [comment]
后续在设置可以自己配置这种页面设置 作为之后版本更新 增强功能之一

**Comment by crowforkotlin** [comment]
dev 版本 后续修复此功能
