### ISSUE TITLE
大佬能多增加一些线路节点吗？

### ISSUE THREAD

**Issue by lhjgege** [crowforkotlin/CopyMangaX#46]
大佬能多增加点线路节点吗？我使用电信移动网络观看加载太慢了。体验效果很差

**Comment by CrowForKotlin** [comment]
晚点我看下 详情可参考 #33

**Comment by fumiama** [comment]
- 第三方应用无法要求官方增加图片节点
- 如果速度慢，您可以尝试使用科学上网手段，首选新加坡

**Comment by lhjgege** [comment]
> * 第三方应用无法要求官方增加图片节点
> * 如果速度慢，您可以尝试使用科学上网手段，首选新加坡

大哥能翻墙就不会来这里说了说明没有呀。
