### ISSUE TITLE
SSL handshake aborted

### ISSUE THREAD

**Issue by DJDQfff** [crowforkotlin/CopyMangaX#50]
**Smartphone (please complete the following information):**
 - Device: vivi y66ia
 - OS: funtouchOs(Android 7.1)
 - AppVersion latest

**Describe the bug**

SSL handshake aborted: ssl=0x61512948: I/O error during system call, Connection reset by peer

**To Reproduce**
Login my my count

**Expected behavior**

**Screenshots**

**Comment by crowforkotlin** [comment]
1：是否开了梯子登录？（建议关掉）
2：或者登录次数过多？（登录过多 会导致失败）
3：手机是否安装了一些证书？
4：可能和自身的网络有关系
