### ISSUE TITLE
有些漫画的图很糊

### ISSUE THREAD

**Issue by LycorisWind** [crowforkotlin/CopyMangaX#59]
![Screenshot_20231017_175006_com crow copymanga](https://github.com/crowforkotlin/CopyMangaX/assets/109772864/4bf54610-2710-4fec-83c2-992a87f21fd7)
![Screenshot_20231017_174713_com crow copymanga](https://github.com/crowforkotlin/CopyMangaX/assets/109772864/9d7fc91c-993f-4915-82ba-ca762fc8ef29)

希望大佬能优化一下

**Comment by crowforkotlin** [comment]
1：请问是什么漫画
2：看图片发现你手机的状态栏仍然存在 没有沉浸式吗？
3：请问Android版本 机型是什么

**Comment by crowforkotlin** [comment]
![048e21f28bc1de8cb464acd2bd4364a](https://github.com/crowforkotlin/CopyMangaX/assets/60876546/3485eaa4-a11a-4c1d-b25b-9eb3a70d45b4)
![7858720a4bdbcae7fedce596907a102](https://github.com/crowforkotlin/CopyMangaX/assets/60876546/2b0fa3fb-b74e-435a-b181-61decbeab039)
预期的效果如上

**Comment by LycorisWind** [comment]
1：漫画名叫：《救赎》
2：沉浸式不太清楚，翻了翻设置，好像没有找到……
3：版本：HarmonyOS 3.0.0，型号是HONOR X10。
4：有时候看着看着漫画的图就模糊了，接连几张图这样，然后又会清晰。
![Screenshot_20231017_193033_com crow copymanga](https://github.com/crowforkotlin/CopyMangaX/assets/109772864/9faf13cd-26ba-4a9d-8e56-21a6bc211942)

**Comment by crowforkotlin** [comment]
问题已排查 加载图片的时候未设置固定的尺寸导致的
此问题后续在漫画阅读器 加载部分 重写实现

**Comment by LycorisWind** [comment]
> 问题已排查 加载图片的时候未设置固定的尺寸导致的 此问题后续在漫画阅读器 加载部分 重写实现

好，谢谢大佬

**Comment by sasakiyori** [comment]
我也遇到过类似的问题，但是我感觉我的情况更像是网络原因导致？中间有几张图比较糊，糊得字都看不太清楚，然后退出去重进有时候就会变清晰了

**Comment by crowforkotlin** [comment]
> 我也遇到过类似的问题，但是我感觉我的情况更像是网络原因导致？中间有几张图比较糊，糊得字都看不太清楚，然后退出去重进有时候就会变清晰了

还是需要重新实现漫画阅读器才能解决此问题 等后续有时间处理了在跟进看看吧

**Comment by moecly** [comment]
> 问题已排查 加载图片的时候未设置固定的尺寸导致的 此问题后续在漫画阅读器 加载部分 重写实现

大佬nb

**Comment by crowforkotlin** [comment]
> > 问题已排查 加载图片的时候未设置固定的尺寸导致的 此问题后续在漫画阅读器 加载部分 重写实现
> 
> 大佬nb

666 我还不如你这个隐藏大佬

**Comment by adsl95** [comment]
还有的漫画不是这样一部分糊一部分没事,是全篇都是糊的,浏览网页版或其他第三方app就没问题说明不是资源的事.
出问题的基本都是韩漫,因为韩漫都是条漫一直往下拉的.
举个例子:请在一次和我结婚,老公.灰姑娘的善良继母.
这两个漫画每一话每一页都是糊的......
自己简单后分析原因在于,如果条漫是一话一百多个图拼的,这种就没事.
有的可能上传的人自己拼过,一话只有十几页但一页特别特别长的,就百分百是糊的,载入的图是低分辨率的.
 

另外再说一个建议,希望可以加入一个设置,选择自己可以缓存多少页,例如现在看的这一页后面自动先缓存20页还是多少.
看这种条漫的时候,流畅度会好很多,因为一话一百多页甚至二百页,如果网偶尔不流畅,就会卡在某一块没载入要等他.....偏偏这种条漫又是不断一直往下拉,一页可能10秒都看不了就下拉了(因为一格画面可能都是三四页拼出来的).
看日漫就没这些事,一页很多格能看一会,这一会里早就缓存好了下一页.

**Comment by crowforkotlin** [comment]
> 还有的漫画不是这样一部分糊一部分没事,是全篇都是糊的,浏览网页版或其他第三方app就没问题说明不是资源的事. 出问题的基本都是韩漫,因为韩漫都是条漫一直往下拉的. 举个例子:请在一次和我结婚,老公.灰姑娘的善良继母. 这两个漫画每一话每一页都是糊的...... 自己简单后分析原因在于,如果条漫是一话一百多个图拼的,这种就没事. 有的可能上传的人自己拼过,一话只有十几页但一页特别特别长的,就百分百是糊的,载入的图是低分辨率的.
> 
> 另外再说一个建议,希望可以加入一个设置,选择自己可以缓存多少页,例如现在看的这一页后面自动先缓存20页还是多少. 看这种条漫的时候,流畅度会好很多,因为一话一百多页甚至二百页,如果网偶尔不流畅,就会卡在某一块没载入要等他.....偏偏这种条漫又是不断一直往下拉,一页可能10秒都看不了就下拉了(因为一格画面可能都是三四页拼出来的). 看日漫就没这些事,一页很多格能看一会,这一会里早就缓存好了下一页.

漫画会糊是因为 设计漫画阅读器的时候没有考虑到 图片的大小尺寸导致 需要手写重新实现，而不是依赖现有框架，这个问题在1.3.0发布后后续会进行跟进 漫画阅读器并修复，另外您的建议我看了 这个也是会在漫画阅读器中跟进下

**Comment by crowforkotlin** [comment]
[此问题已修复 - Dev分支，1.3.2发布后正常使用](https://github.com/crowforkotlin/CopyMangaX/blob/d2c7af05ad5bcdccfb8de88cdd374c51e4c4c545/lib_mangax/src/main/kotlin/com/crow/mangax/ui/adapter/MangaCoilVH.kt)
