### ISSUE TITLE
热度应该是显示错了吧

### ISSUE THREAD

**Issue by linrealp** [crowforkotlin/CopyMangaX#70]
热度应该是错了把，少除10000？
![90F8D5DE8C21A932714D5F075EFB5D46](https://github.com/crowforkotlin/CopyMangaX/assets/44330725/d68bb0fa-7a7d-4596-bf77-7c280860477a)
![0D996579C24DDFA83EA0C7B9FB3A2E67](https://github.com/crowforkotlin/CopyMangaX/assets/44330725/19d8fd7c-e0ff-4f35-80e4-151c154c891f)

**Comment by crowforkotlin** [comment]
内部版本1.2.8已经解决此问题
