### ISSUE TITLE
開始閱讀bug&建議

### ISSUE THREAD

**Issue by 21802961** [crowforkotlin/CopyMangaX#75]
設備
Android版本11
Xperia 5 iii

我是第一次用這軟體
按開始閱讀時會直接跳到第一章
![Screenshot_20240101-100124](https://github.com/crowforkotlin/CopyMangaX/assets/155337624/b6cbc08d-1d6a-493c-b0af-a1c141402579)
![Screenshot_20240101-100146](https://github.com/crowforkotlin/CopyMangaX/assets/155337624/7b655c63-f081-4618-b6b6-bae7f70e9120)

建議
可以跳頁數
在閱讀器裡面
介面有下一章可以用

**Comment by crowforkotlin** [comment]
好的，已跟进
