### ISSUE TITLE
在退出阅读后''站点设置（节点）''中的选项被重置

### ISSUE THREAD

**Issue by Gunjo27** [crowforkotlin/CopyMangaX#77]
**Smartphone (please complete the following information):**
 - AppVersion [e.g. 22]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by crowforkotlin** [comment]
[此问题已修复](https://github.com/crowforkotlin/CopyMangaX/blob/d2c7af05ad5bcdccfb8de88cdd374c51e4c4c545/module_main/src/main/kotlin/com/crow/module_main/ui/viewmodel/MainViewModel.kt#L43)
