### ISSUE TITLE
动画播放全屏没返回按钮

### ISSUE THREAD

**Issue by lhjgege** [crowforkotlin/CopyMangaX#81]
1.在最新版本1.3.2中全屏动画播放无返回按钮只有一个有点不习惯
2.应用后期会给出用户自己添加源的功能嘛？
3.能否适配异次元漫画和阅读漫画源呢？
4.看到应用用也有小说是否可以适配阅读源呢？

**Comment by crowforkotlin** [comment]
1：后续跟进
2：CopyMangaX不考虑扩展源，只用这一个
3：等CopyMangaX完成后后续在开个新的项目再看情况决定是否做多源的MangaReader

**Comment by lhjgege** [comment]
如果能适配多源那么看漫画的选择会很多，只有一个源的话漫画选择很少。有时候这个源上的漫画不一定是使用者想看的。
非常期待你的MangaReader项目。

**Comment by crowforkotlin** [comment]
其实拷贝已经够用了共计收录接近4万本Comic只是更新较慢，MangaReader只是以后的一个计划把，实行的可能性很低，毕竟就这一个项目就已经够折腾了，工作量很大，当拷贝完成后后续有新的拷贝计划，但是还远着

**Comment by lhjgege** [comment]
确实是一个项目都已经够折腾了而且没有其他开发者共同开发，主要是还是使用者有点低了。如果能和阅读一样的用户数那么加入开发的人会很多。就会提很多pr了。

**Comment by lhjgege** [comment]
但是在这里感谢你的开源精神。

**Comment by crowforkotlin** [comment]
> 确实是一个项目都已经够折腾了而且没有其他开发者共同开发，主要是还是使用者有点低了。如果能和阅读一样的用户数那么加入开发的人会很多。就会提很多pr了。

其实该项目的初衷仅用于学习，现在也是如此、只不过最近用户量是有在增加所以感觉现在像是被迫赶工一样。 写屎山的话这些功能早就写完了

**Comment by lhjgege** [comment]
毕竟是自己的第一个开源项目，也不想写的太烂不然后期增加功能或者修复问题再去看代码都是一个问题。

**Comment by kirito5210** [comment]
专注于一个源的情况下软件会更好用，那种多源的软件网上已经有很多了，可以自己找一下，但是源一多通常会有非常多用不了的源，维护也跟不上，不如专精一个

**Comment by lhjgege** [comment]
![image](https://github.com/crowforkotlin/CopyMangaX/assets/20966610/d3d49a0b-72c7-4c6d-afb1-abc1dd2b53d0)
你好项目是不是缺少了文件呀，我编译显示lib_mangax中找不到src/main/jni/OpenCC/src/BinaryDict.cpp文件

**Comment by crowforkotlin** [comment]
![image](https://github.com/crowforkotlin/CopyMangaX/assets/60876546/4d6f777f-499d-4a00-b089-001a898d56a3)


> ![image](https://private-user-images.githubusercontent.com/20966610/308830533-d3d49a0b-72c7-4c6d-afb1-abc1dd2b53d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTE0OTcsIm5iZiI6MTcwOTE5MTE5NywicGF0aCI6Ii8yMDk2NjYxMC8zMDg4MzA1MzMtZDNkNDlhMGItNzJjNy00YzZkLWFmYjEtYWJjMWRkMmI1M2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOWRmODUyZTk1ZmY0ZjkzMDQ4OGNjZTY3MTFhNTE3Y2EzNjIzODE1Y2FmM2U3ZDQ0MzU4ZDg5NzRmYjNmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2LvHUcXsRwS-nkZ8hgMfIY_3RkhtY8BH763NptwAOA) 你好项目是不是缺少了文件呀，我编译显示lib_mangax中找不到src/main/jni/OpenCC/src/BinaryDict.cpp文件

**Comment by lhjgege** [comment]
已经输入过了

**Comment by lhjgege** [comment]
![image](https://github.com/crowforkotlin/CopyMangaX/assets/20966610/4c81f6db-0bba-4b6e-bcfe-5e8eb92877bf)

**Comment by crowforkotlin** [comment]
> 已经输入过了

我之前也遇到过这个问题，不太好处理，你有远程工具吗邮箱发给我我现在给你看看

**Comment by lhjgege** [comment]
没有哦，

**Comment by lhjgege** [comment]
你是怎么处理的。直接告诉我一下，我看怎么弄

**Comment by crowforkotlin** [comment]
> 你是怎么处理的。直接告诉我一下，我看怎么弄

都忘了都，得现场调试看看

**Comment by lhjgege** [comment]
方便么直接把
![image](https://github.com/crowforkotlin/CopyMangaX/assets/20966610/a90169d2-52eb-4910-861e-6bd6a271ac66)
这个打包上来我下载看能运行起来不

**Comment by crowforkotlin** [comment]
> 方便么直接把 ![image](https://private-user-images.githubusercontent.com/20966610/308833633-a90169d2-52eb-4910-861e-6bd6a271ac66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTQ5MDIsIm5iZiI6MTcwOTE5NDYwMiwicGF0aCI6Ii8yMDk2NjYxMC8zMDg4MzM2MzMtYTkwMTY5ZDItNTJlYi00OTEwLTg2MWUtNmJkNmEyNzFhYzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA4MTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkM2Y2MGU0OTExNDVhOWE1NTdlYTJhMDNmM2E1ODE2YjkyZTRkNTMwY2M3M2VmZGQyMzJkMmZjMDgxYjIwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9q30D-8awq10o0v4qnAGjO2A6Y2eWdDKtu2ql8dIHE) 这个打包上来我下载看能运行起来不

删除OpenCC文件夹

1： git init
2:  git submodule add https://github.com/BYVoid/OpenCC.git lib_mangax/src/main/jni/OpenCC

**Comment by lhjgege** [comment]
OK
