### ISSUE TITLE
有关评论区

### ISSUE THREAD

**Issue by Gunjo27** [crowforkotlin/CopyMangaX#99]
非常感谢您加入了左右滑动阅读方式，不过有一部分人习惯使用左手，导致经常调出评论区。
可以请您考虑加入关闭评论区的设置吗？

**Comment by crowforkotlin** [comment]
已经禁止滑动滑出评论区 https://github.com/crowforkotlin/CopyMangaX/blob/24aed9ec12ea1868bcd662a5ab00be77134a6dcc/module_book/src/main/kotlin/com/crow/module_book/ui/activity/ComicActivity.kt#L340
